# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BowSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Bow', '0.1.0'

  # Pods for BowSample

  target 'BowSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
